services:
  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=50880930
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
  redis:
    image: redis:8-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:50880930@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started

volumes:
  db-data: