// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_get_account_by_owner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByOwnerRequest) Reset() {
	*x = GetAccountByOwnerRequest{}
	mi := &file_rpc_get_account_by_owner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByOwnerRequest) ProtoMessage() {}

func (x *GetAccountByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_account_by_owner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_account_by_owner_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByOwnerRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetAccountByOwnerRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAccountByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByOwnerResponse) Reset() {
	*x = GetAccountByOwnerResponse{}
	mi := &file_rpc_get_account_by_owner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByOwnerResponse) ProtoMessage() {}

func (x *GetAccountByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_account_by_owner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_account_by_owner_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByOwnerResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_rpc_get_account_by_owner_proto protoreflect.FileDescriptor

const file_rpc_get_account_by_owner_proto_rawDesc = "" +
	"\n" +
	"\x1erpc_get_account_by_owner.proto\x12\x02pb\x1a\raccount.proto\"L\n" +
	"\x18GetAccountByOwnerRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"B\n" +
	"\x19GetAccountByOwnerResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccountB!Z\x1fgithub.com/oldlay/simplebank/pbb\x06proto3"

var (
	file_rpc_get_account_by_owner_proto_rawDescOnce sync.Once
	file_rpc_get_account_by_owner_proto_rawDescData []byte
)

func file_rpc_get_account_by_owner_proto_rawDescGZIP() []byte {
	file_rpc_get_account_by_owner_proto_rawDescOnce.Do(func() {
		file_rpc_get_account_by_owner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_account_by_owner_proto_rawDesc), len(file_rpc_get_account_by_owner_proto_rawDesc)))
	})
	return file_rpc_get_account_by_owner_proto_rawDescData
}

var file_rpc_get_account_by_owner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_account_by_owner_proto_goTypes = []any{
	(*GetAccountByOwnerRequest)(nil),  // 0: pb.GetAccountByOwnerRequest
	(*GetAccountByOwnerResponse)(nil), // 1: pb.GetAccountByOwnerResponse
	(*Account)(nil),                   // 2: pb.Account
}
var file_rpc_get_account_by_owner_proto_depIdxs = []int32{
	2, // 0: pb.GetAccountByOwnerResponse.account:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_account_by_owner_proto_init() }
func file_rpc_get_account_by_owner_proto_init() {
	if File_rpc_get_account_by_owner_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_account_by_owner_proto_rawDesc), len(file_rpc_get_account_by_owner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_account_by_owner_proto_goTypes,
		DependencyIndexes: file_rpc_get_account_by_owner_proto_depIdxs,
		MessageInfos:      file_rpc_get_account_by_owner_proto_msgTypes,
	}.Build()
	File_rpc_get_account_by_owner_proto = out.File
	file_rpc_get_account_by_owner_proto_goTypes = nil
	file_rpc_get_account_by_owner_proto_depIdxs = nil
}
