// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_get_exchange_rate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_rpc_get_exchange_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_exchange_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_exchange_rate_proto_rawDescGZIP(), []int{0}
}

type GetExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Rates         map[string]float64     `protobuf:"bytes,3,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateResponse) Reset() {
	*x = GetExchangeRateResponse{}
	mi := &file_rpc_get_exchange_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateResponse) ProtoMessage() {}

func (x *GetExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_exchange_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*GetExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_exchange_rate_proto_rawDescGZIP(), []int{1}
}

func (x *GetExchangeRateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetExchangeRateResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetExchangeRateResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_rpc_get_exchange_rate_proto protoreflect.FileDescriptor

const file_rpc_get_exchange_rate_proto_rawDesc = "" +
	"\n" +
	"\x1brpc_get_exchange_rate.proto\x12\x02pb\"\x18\n" +
	"\x16GetExchangeRateRequest\"\xbd\x01\n" +
	"\x17GetExchangeRateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12<\n" +
	"\x05rates\x18\x03 \x03(\v2&.pb.GetExchangeRateResponse.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B!Z\x1fgithub.com/oldlay/simplebank/pbb\x06proto3"

var (
	file_rpc_get_exchange_rate_proto_rawDescOnce sync.Once
	file_rpc_get_exchange_rate_proto_rawDescData []byte
)

func file_rpc_get_exchange_rate_proto_rawDescGZIP() []byte {
	file_rpc_get_exchange_rate_proto_rawDescOnce.Do(func() {
		file_rpc_get_exchange_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_exchange_rate_proto_rawDesc), len(file_rpc_get_exchange_rate_proto_rawDesc)))
	})
	return file_rpc_get_exchange_rate_proto_rawDescData
}

var file_rpc_get_exchange_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_get_exchange_rate_proto_goTypes = []any{
	(*GetExchangeRateRequest)(nil),  // 0: pb.GetExchangeRateRequest
	(*GetExchangeRateResponse)(nil), // 1: pb.GetExchangeRateResponse
	nil,                             // 2: pb.GetExchangeRateResponse.RatesEntry
}
var file_rpc_get_exchange_rate_proto_depIdxs = []int32{
	2, // 0: pb.GetExchangeRateResponse.rates:type_name -> pb.GetExchangeRateResponse.RatesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_exchange_rate_proto_init() }
func file_rpc_get_exchange_rate_proto_init() {
	if File_rpc_get_exchange_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_exchange_rate_proto_rawDesc), len(file_rpc_get_exchange_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_exchange_rate_proto_goTypes,
		DependencyIndexes: file_rpc_get_exchange_rate_proto_depIdxs,
		MessageInfos:      file_rpc_get_exchange_rate_proto_msgTypes,
	}.Build()
	File_rpc_get_exchange_rate_proto = out.File
	file_rpc_get_exchange_rate_proto_goTypes = nil
	file_rpc_get_exchange_rate_proto_depIdxs = nil
}
