// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_list_account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int64                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRequest) Reset() {
	*x = ListAccountRequest{}
	mi := &file_rpc_list_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRequest) ProtoMessage() {}

func (x *ListAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRequest.ProtoReflect.Descriptor instead.
func (*ListAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_account_proto_rawDescGZIP(), []int{0}
}

func (x *ListAccountRequest) GetPageId() int64 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListAccountRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountResponse) Reset() {
	*x = ListAccountResponse{}
	mi := &file_rpc_list_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountResponse) ProtoMessage() {}

func (x *ListAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountResponse.ProtoReflect.Descriptor instead.
func (*ListAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_account_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_rpc_list_account_proto protoreflect.FileDescriptor

const file_rpc_list_account_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_list_account.proto\x12\x02pb\x1a\raccount.proto\"J\n" +
	"\x12ListAccountRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\x03R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\">\n" +
	"\x13ListAccountResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.pb.AccountR\baccountsB!Z\x1fgithub.com/oldlay/simplebank/pbb\x06proto3"

var (
	file_rpc_list_account_proto_rawDescOnce sync.Once
	file_rpc_list_account_proto_rawDescData []byte
)

func file_rpc_list_account_proto_rawDescGZIP() []byte {
	file_rpc_list_account_proto_rawDescOnce.Do(func() {
		file_rpc_list_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_account_proto_rawDesc), len(file_rpc_list_account_proto_rawDesc)))
	})
	return file_rpc_list_account_proto_rawDescData
}

var file_rpc_list_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_account_proto_goTypes = []any{
	(*ListAccountRequest)(nil),  // 0: pb.ListAccountRequest
	(*ListAccountResponse)(nil), // 1: pb.ListAccountResponse
	(*Account)(nil),             // 2: pb.Account
}
var file_rpc_list_account_proto_depIdxs = []int32{
	2, // 0: pb.ListAccountResponse.accounts:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_account_proto_init() }
func file_rpc_list_account_proto_init() {
	if File_rpc_list_account_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_account_proto_rawDesc), len(file_rpc_list_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_account_proto_goTypes,
		DependencyIndexes: file_rpc_list_account_proto_depIdxs,
		MessageInfos:      file_rpc_list_account_proto_msgTypes,
	}.Build()
	File_rpc_list_account_proto = out.File
	file_rpc_list_account_proto_goTypes = nil
	file_rpc_list_account_proto_depIdxs = nil
}
