// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_delete_account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_rpc_delete_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_delete_account_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteResult  string                 `protobuf:"bytes,1,opt,name=delete_result,json=deleteResult,proto3" json:"delete_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_rpc_delete_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_delete_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_delete_account_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteAccountResponse) GetDeleteResult() string {
	if x != nil {
		return x.DeleteResult
	}
	return ""
}

var File_rpc_delete_account_proto protoreflect.FileDescriptor

const file_rpc_delete_account_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_delete_account.proto\x12\x02pb\"&\n" +
	"\x14DeleteAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x15DeleteAccountResponse\x12#\n" +
	"\rdelete_result\x18\x01 \x01(\tR\fdeleteResultB!Z\x1fgithub.com/oldlay/simplebank/pbb\x06proto3"

var (
	file_rpc_delete_account_proto_rawDescOnce sync.Once
	file_rpc_delete_account_proto_rawDescData []byte
)

func file_rpc_delete_account_proto_rawDescGZIP() []byte {
	file_rpc_delete_account_proto_rawDescOnce.Do(func() {
		file_rpc_delete_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_delete_account_proto_rawDesc), len(file_rpc_delete_account_proto_rawDesc)))
	})
	return file_rpc_delete_account_proto_rawDescData
}

var file_rpc_delete_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_delete_account_proto_goTypes = []any{
	(*DeleteAccountRequest)(nil),  // 0: pb.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 1: pb.DeleteAccountResponse
}
var file_rpc_delete_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_delete_account_proto_init() }
func file_rpc_delete_account_proto_init() {
	if File_rpc_delete_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_delete_account_proto_rawDesc), len(file_rpc_delete_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_delete_account_proto_goTypes,
		DependencyIndexes: file_rpc_delete_account_proto_depIdxs,
		MessageInfos:      file_rpc_delete_account_proto_msgTypes,
	}.Build()
	File_rpc_delete_account_proto = out.File
	file_rpc_delete_account_proto_goTypes = nil
	file_rpc_delete_account_proto_depIdxs = nil
}
