// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpc_create_transfer.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToOwner       string                 `protobuf:"bytes,2,opt,name=to_owner,json=toOwner,proto3" json:"to_owner,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,3,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_rpc_create_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetToOwner() string {
	if x != nil {
		return x.ToOwner
	}
	return ""
}

func (x *CreateTransferRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	FromAccount   *Account               `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     *Account               `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	FromEntry     *Entry                 `protobuf:"bytes,4,opt,name=from_entry,json=fromEntry,proto3" json:"from_entry,omitempty"`
	ToEntry       *Entry                 `protobuf:"bytes,5,opt,name=to_entry,json=toEntry,proto3" json:"to_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_rpc_create_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *CreateTransferResponse) GetFromAccount() *Account {
	if x != nil {
		return x.FromAccount
	}
	return nil
}

func (x *CreateTransferResponse) GetToAccount() *Account {
	if x != nil {
		return x.ToAccount
	}
	return nil
}

func (x *CreateTransferResponse) GetFromEntry() *Entry {
	if x != nil {
		return x.FromEntry
	}
	return nil
}

func (x *CreateTransferResponse) GetToEntry() *Entry {
	if x != nil {
		return x.ToEntry
	}
	return nil
}

var File_rpc_create_transfer_proto protoreflect.FileDescriptor

const file_rpc_create_transfer_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_create_transfer.proto\x12\x02pb\x1a\raccount.proto\x1a\x0etransfer.proto\x1a\ventry.proto\x1a\x19google/type/decimal.proto\"\xc5\x01\n" +
	"\x15CreateTransferRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\x19\n" +
	"\bto_owner\x18\x02 \x01(\tR\atoOwner\x12\x1f\n" +
	"\vto_currency\x18\x03 \x01(\tR\n" +
	"toCurrency\x12,\n" +
	"\x06amount\x18\x04 \x01(\v2\x14.google.type.DecimalR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xee\x01\n" +
	"\x16CreateTransferResponse\x12(\n" +
	"\btransfer\x18\x01 \x01(\v2\f.pb.TransferR\btransfer\x12.\n" +
	"\ffrom_account\x18\x02 \x01(\v2\v.pb.AccountR\vfromAccount\x12*\n" +
	"\n" +
	"to_account\x18\x03 \x01(\v2\v.pb.AccountR\ttoAccount\x12(\n" +
	"\n" +
	"from_entry\x18\x04 \x01(\v2\t.pb.EntryR\tfromEntry\x12$\n" +
	"\bto_entry\x18\x05 \x01(\v2\t.pb.EntryR\atoEntryB!Z\x1fgithub.com/oldlay/simplebank/pbb\x06proto3"

var (
	file_rpc_create_transfer_proto_rawDescOnce sync.Once
	file_rpc_create_transfer_proto_rawDescData []byte
)

func file_rpc_create_transfer_proto_rawDescGZIP() []byte {
	file_rpc_create_transfer_proto_rawDescOnce.Do(func() {
		file_rpc_create_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_transfer_proto_rawDesc), len(file_rpc_create_transfer_proto_rawDesc)))
	})
	return file_rpc_create_transfer_proto_rawDescData
}

var file_rpc_create_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil),  // 0: pb.CreateTransferRequest
	(*CreateTransferResponse)(nil), // 1: pb.CreateTransferResponse
	(*decimal.Decimal)(nil),        // 2: google.type.Decimal
	(*Transfer)(nil),               // 3: pb.Transfer
	(*Account)(nil),                // 4: pb.Account
	(*Entry)(nil),                  // 5: pb.Entry
}
var file_rpc_create_transfer_proto_depIdxs = []int32{
	2, // 0: pb.CreateTransferRequest.amount:type_name -> google.type.Decimal
	3, // 1: pb.CreateTransferResponse.transfer:type_name -> pb.Transfer
	4, // 2: pb.CreateTransferResponse.from_account:type_name -> pb.Account
	4, // 3: pb.CreateTransferResponse.to_account:type_name -> pb.Account
	5, // 4: pb.CreateTransferResponse.from_entry:type_name -> pb.Entry
	5, // 5: pb.CreateTransferResponse.to_entry:type_name -> pb.Entry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_create_transfer_proto_init() }
func file_rpc_create_transfer_proto_init() {
	if File_rpc_create_transfer_proto != nil {
		return
	}
	file_account_proto_init()
	file_transfer_proto_init()
	file_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_transfer_proto_rawDesc), len(file_rpc_create_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_transfer_proto_goTypes,
		DependencyIndexes: file_rpc_create_transfer_proto_depIdxs,
		MessageInfos:      file_rpc_create_transfer_proto_msgTypes,
	}.Build()
	File_rpc_create_transfer_proto = out.File
	file_rpc_create_transfer_proto_goTypes = nil
	file_rpc_create_transfer_proto_depIdxs = nil
}
